
export default sampledata = [
  {
    firstName: "",
    lastName: "",
    email: "",
    companyName: "",
    products: "",
    phone: "",
  },
  {
    firstName: "",
    lastName: "",
    email: "",
    companyName: "",
    products: "",
    phone: "",
  },
  {
    firstName : "",
    lastName : "",
    email: "",
    companyName : "",
    products: "",
    phone : "",
},
{
    firstName : "",
    lastName : "",
    email: "",
    companyName : "",
    products: "",
    phone : "",
},
{
    firstName : "",
    lastName : "",
    email: "",
    companyName : "",
    products: "",
    phone : "",
},
{
    firstName : "",
    lastName : "",
    email: "",
    companyName : "",
    products: "",
    phone : "",
},
{
    firstName : "",
    lastName : "",
    email: "",
    companyName : "",
    products: "",
    phone : "",
},
];
